demo/config/routes.rb
Demo::Application.routes.draw do
  get "say/hello"

  get "say/goodbye"

end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

demo/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
    @files = Dir.glob('*')
  end

  def goodbye
  end
end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/say_helper.rb
module SayHelper
end

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

demo/app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>
<p>Find me in app/views/say/goodbye.html.erb</p>
<hr>

<h1>Goodbye!</h1>
<p>It was nice having you here.</p>
<hr>

<p>Say <a href="/say/hello">Hello</a>!</p>

demo/app/views/say/hello.html.erb
<h1>Say#hello</h1>
<p>Find me in app/views/say/hello.html.erb</p>
<hr>

<h1>Hello from Rails!</h1>
<p>It is now <%= Time.now %> (data from view)</p>
<p>It is now <%= @time %> (data from controller)</p>
<hr>

<p>Say <a href="/say/goodbye">Goodbye</a>!</p>
<p>Its time to say <%= link_to "Goodbye", say_goodbye_path %>!</p>
<hr>

<h1>Concatenation</h1>
<p>
  <ul>
    <li><%= 1+2 %></li>
    <li><%= "cow" + "boy" %></li>
    <li><%= 1.hour.from_now %></li>
  </ul>
</p>
<hr>

<h1>File</h1>
<ul>
  <% for file in @files %>
    <li>file name is:<%= file %></li> 
  <% end %>
</ul>